// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueNull int32

const (
	ValueNull_NULL_VALUE ValueNull = 0
)

// Enum value maps for ValueNull.
var (
	ValueNull_name = map[int32]string{
		0: "NULL_VALUE",
	}
	ValueNull_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x ValueNull) Enum() *ValueNull {
	p := new(ValueNull)
	*p = x
	return p
}

func (x ValueNull) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueNull) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (ValueNull) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x ValueNull) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueNull.Descriptor instead.
func (ValueNull) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

type StatisticKind int32

const (
	StatisticKind_Histogram StatisticKind = 0
	StatisticKind_Summary   StatisticKind = 1
)

// Enum value maps for StatisticKind.
var (
	StatisticKind_name = map[int32]string{
		0: "Histogram",
		1: "Summary",
	}
	StatisticKind_value = map[string]int32{
		"Histogram": 0,
		"Summary":   1,
	}
)

func (x StatisticKind) Enum() *StatisticKind {
	p := new(StatisticKind)
	*p = x
	return p
}

func (x StatisticKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatisticKind) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (StatisticKind) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x StatisticKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatisticKind.Descriptor instead.
func (StatisticKind) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

type Metric_Kind int32

const (
	Metric_Incremental Metric_Kind = 0
	Metric_Absolute    Metric_Kind = 1
)

// Enum value maps for Metric_Kind.
var (
	Metric_Kind_name = map[int32]string{
		0: "Incremental",
		1: "Absolute",
	}
	Metric_Kind_value = map[string]int32{
		"Incremental": 0,
		"Absolute":    1,
	}
)

func (x Metric_Kind) Enum() *Metric_Kind {
	p := new(Metric_Kind)
	*p = x
	return p
}

func (x Metric_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[2].Descriptor()
}

func (Metric_Kind) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[2]
}

func (x Metric_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_Kind.Descriptor instead.
func (Metric_Kind) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14, 0}
}

type EventArray struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Events:
	//
	//	*EventArray_Logs
	//	*EventArray_Metrics
	//	*EventArray_Traces
	Events        isEventArray_Events `protobuf_oneof:"events"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventArray) Reset() {
	*x = EventArray{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventArray) ProtoMessage() {}

func (x *EventArray) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventArray.ProtoReflect.Descriptor instead.
func (*EventArray) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventArray) GetEvents() isEventArray_Events {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventArray) GetLogs() *LogArray {
	if x != nil {
		if x, ok := x.Events.(*EventArray_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *EventArray) GetMetrics() *MetricArray {
	if x != nil {
		if x, ok := x.Events.(*EventArray_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *EventArray) GetTraces() *TraceArray {
	if x != nil {
		if x, ok := x.Events.(*EventArray_Traces); ok {
			return x.Traces
		}
	}
	return nil
}

type isEventArray_Events interface {
	isEventArray_Events()
}

type EventArray_Logs struct {
	Logs *LogArray `protobuf:"bytes,1,opt,name=logs,proto3,oneof"`
}

type EventArray_Metrics struct {
	Metrics *MetricArray `protobuf:"bytes,2,opt,name=metrics,proto3,oneof"`
}

type EventArray_Traces struct {
	Traces *TraceArray `protobuf:"bytes,3,opt,name=traces,proto3,oneof"`
}

func (*EventArray_Logs) isEventArray_Events() {}

func (*EventArray_Metrics) isEventArray_Events() {}

func (*EventArray_Traces) isEventArray_Events() {}

type LogArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*Log                 `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogArray) Reset() {
	*x = LogArray{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogArray) ProtoMessage() {}

func (x *LogArray) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogArray.ProtoReflect.Descriptor instead.
func (*LogArray) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *LogArray) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type MetricArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricArray) Reset() {
	*x = MetricArray{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricArray) ProtoMessage() {}

func (x *MetricArray) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricArray.ProtoReflect.Descriptor instead.
func (*MetricArray) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *MetricArray) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type TraceArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*Trace               `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceArray) Reset() {
	*x = TraceArray{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceArray) ProtoMessage() {}

func (x *TraceArray) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceArray.ProtoReflect.Descriptor instead.
func (*TraceArray) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *TraceArray) GetTraces() []*Trace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type EventWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventWrapper_Log
	//	*EventWrapper_Metric
	//	*EventWrapper_Trace
	Event         isEventWrapper_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventWrapper) Reset() {
	*x = EventWrapper{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventWrapper) ProtoMessage() {}

func (x *EventWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventWrapper.ProtoReflect.Descriptor instead.
func (*EventWrapper) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *EventWrapper) GetEvent() isEventWrapper_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventWrapper) GetLog() *Log {
	if x != nil {
		if x, ok := x.Event.(*EventWrapper_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *EventWrapper) GetMetric() *Metric {
	if x != nil {
		if x, ok := x.Event.(*EventWrapper_Metric); ok {
			return x.Metric
		}
	}
	return nil
}

func (x *EventWrapper) GetTrace() *Trace {
	if x != nil {
		if x, ok := x.Event.(*EventWrapper_Trace); ok {
			return x.Trace
		}
	}
	return nil
}

type isEventWrapper_Event interface {
	isEventWrapper_Event()
}

type EventWrapper_Log struct {
	Log *Log `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type EventWrapper_Metric struct {
	Metric *Metric `protobuf:"bytes,2,opt,name=metric,proto3,oneof"`
}

type EventWrapper_Trace struct {
	Trace *Trace `protobuf:"bytes,3,opt,name=trace,proto3,oneof"`
}

func (*EventWrapper_Log) isEventWrapper_Event() {}

func (*EventWrapper_Metric) isEventWrapper_Event() {}

func (*EventWrapper_Trace) isEventWrapper_Event() {}

type Log struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated, use value instead
	Fields map[string]*Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Value  *Value            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Deprecated: Marked as deprecated in event.proto.
	Metadata      *Value    `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MetadataFull  *Metadata `protobuf:"bytes,4,opt,name=metadata_full,json=metadataFull,proto3" json:"metadata_full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *Log) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Log) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Deprecated: Marked as deprecated in event.proto.
func (x *Log) GetMetadata() *Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Log) GetMetadataFull() *Metadata {
	if x != nil {
		return x.MetadataFull
	}
	return nil
}

type Trace struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Fields map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in event.proto.
	Metadata      *Value    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MetadataFull  *Metadata `protobuf:"bytes,3,opt,name=metadata_full,json=metadataFull,proto3" json:"metadata_full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *Trace) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Deprecated: Marked as deprecated in event.proto.
func (x *Trace) GetMetadata() *Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Trace) GetMetadataFull() *Metadata {
	if x != nil {
		return x.MetadataFull
	}
	return nil
}

type ValueMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueMap) Reset() {
	*x = ValueMap{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueMap) ProtoMessage() {}

func (x *ValueMap) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueMap.ProtoReflect.Descriptor instead.
func (*ValueMap) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *ValueMap) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ValueArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Value               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueArray) Reset() {
	*x = ValueArray{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueArray) ProtoMessage() {}

func (x *ValueArray) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueArray.ProtoReflect.Descriptor instead.
func (*ValueArray) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *ValueArray) GetItems() []*Value {
	if x != nil {
		return x.Items
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_RawBytes
	//	*Value_Timestamp
	//	*Value_Integer
	//	*Value_Float
	//	*Value_Boolean
	//	*Value_Map
	//	*Value_Array
	//	*Value_Null
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetRawBytes() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_RawBytes); ok {
			return x.RawBytes
		}
	}
	return nil
}

func (x *Value) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*Value_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *Value) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *Value) GetFloat() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *Value) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *Value) GetMap() *ValueMap {
	if x != nil {
		if x, ok := x.Kind.(*Value_Map); ok {
			return x.Map
		}
	}
	return nil
}

func (x *Value) GetArray() *ValueArray {
	if x != nil {
		if x, ok := x.Kind.(*Value_Array); ok {
			return x.Array
		}
	}
	return nil
}

func (x *Value) GetNull() ValueNull {
	if x != nil {
		if x, ok := x.Kind.(*Value_Null); ok {
			return x.Null
		}
	}
	return ValueNull_NULL_VALUE
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_RawBytes struct {
	RawBytes []byte `protobuf:"bytes,1,opt,name=raw_bytes,json=rawBytes,proto3,oneof"`
}

type Value_Timestamp struct {
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3,oneof"`
}

type Value_Integer struct {
	Integer int64 `protobuf:"varint,4,opt,name=integer,proto3,oneof"`
}

type Value_Float struct {
	Float float64 `protobuf:"fixed64,5,opt,name=float,proto3,oneof"`
}

type Value_Boolean struct {
	Boolean bool `protobuf:"varint,6,opt,name=boolean,proto3,oneof"`
}

type Value_Map struct {
	Map *ValueMap `protobuf:"bytes,7,opt,name=map,proto3,oneof"`
}

type Value_Array struct {
	Array *ValueArray `protobuf:"bytes,8,opt,name=array,proto3,oneof"`
}

type Value_Null struct {
	Null ValueNull `protobuf:"varint,9,opt,name=null,proto3,enum=event.ValueNull,oneof"`
}

func (*Value_RawBytes) isValue_Kind() {}

func (*Value_Timestamp) isValue_Kind() {}

func (*Value_Integer) isValue_Kind() {}

func (*Value_Float) isValue_Kind() {}

func (*Value_Boolean) isValue_Kind() {}

func (*Value_Map) isValue_Kind() {}

func (*Value_Array) isValue_Kind() {}

func (*Value_Null) isValue_Kind() {}

type DatadogOriginMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginProduct  *uint32                `protobuf:"varint,1,opt,name=origin_product,json=originProduct,proto3,oneof" json:"origin_product,omitempty"`
	OriginCategory *uint32                `protobuf:"varint,2,opt,name=origin_category,json=originCategory,proto3,oneof" json:"origin_category,omitempty"`
	OriginService  *uint32                `protobuf:"varint,3,opt,name=origin_service,json=originService,proto3,oneof" json:"origin_service,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DatadogOriginMetadata) Reset() {
	*x = DatadogOriginMetadata{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatadogOriginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatadogOriginMetadata) ProtoMessage() {}

func (x *DatadogOriginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatadogOriginMetadata.ProtoReflect.Descriptor instead.
func (*DatadogOriginMetadata) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *DatadogOriginMetadata) GetOriginProduct() uint32 {
	if x != nil && x.OriginProduct != nil {
		return *x.OriginProduct
	}
	return 0
}

func (x *DatadogOriginMetadata) GetOriginCategory() uint32 {
	if x != nil && x.OriginCategory != nil {
		return *x.OriginCategory
	}
	return 0
}

func (x *DatadogOriginMetadata) GetOriginService() uint32 {
	if x != nil && x.OriginService != nil {
		return *x.OriginService
	}
	return 0
}

type Secrets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]string      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secrets) Reset() {
	*x = Secrets{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secrets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secrets) ProtoMessage() {}

func (x *Secrets) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secrets.ProtoReflect.Descriptor instead.
func (*Secrets) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *Secrets) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type OutputId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	Port          *string                `protobuf:"bytes,2,opt,name=port,proto3,oneof" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputId) Reset() {
	*x = OutputId{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputId) ProtoMessage() {}

func (x *OutputId) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputId.ProtoReflect.Descriptor instead.
func (*OutputId) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *OutputId) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *OutputId) GetPort() string {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return ""
}

type Metadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Value                 *Value                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	DatadogOriginMetadata *DatadogOriginMetadata `protobuf:"bytes,2,opt,name=datadog_origin_metadata,json=datadogOriginMetadata,proto3" json:"datadog_origin_metadata,omitempty"`
	SourceId              *string                `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	SourceType            *string                `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3,oneof" json:"source_type,omitempty"`
	UpstreamId            *OutputId              `protobuf:"bytes,5,opt,name=upstream_id,json=upstreamId,proto3" json:"upstream_id,omitempty"`
	Secrets               *Secrets               `protobuf:"bytes,6,opt,name=secrets,proto3" json:"secrets,omitempty"`
	SourceEventId         []byte                 `protobuf:"bytes,7,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *Metadata) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metadata) GetDatadogOriginMetadata() *DatadogOriginMetadata {
	if x != nil {
		return x.DatadogOriginMetadata
	}
	return nil
}

func (x *Metadata) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *Metadata) GetSourceType() string {
	if x != nil && x.SourceType != nil {
		return *x.SourceType
	}
	return ""
}

func (x *Metadata) GetUpstreamId() *OutputId {
	if x != nil {
		return x.UpstreamId
	}
	return nil
}

func (x *Metadata) GetSecrets() *Secrets {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *Metadata) GetSourceEventId() []byte {
	if x != nil {
		return x.SourceEventId
	}
	return nil
}

type Metric struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TagsV1    map[string]string      `protobuf:"bytes,3,rep,name=tags_v1,json=tagsV1,proto3" json:"tags_v1,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TagsV2    map[string]*TagValues  `protobuf:"bytes,20,rep,name=tags_v2,json=tagsV2,proto3" json:"tags_v2,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Kind      Metric_Kind            `protobuf:"varint,4,opt,name=kind,proto3,enum=event.Metric_Kind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Metric_Counter
	//	*Metric_Gauge
	//	*Metric_Set
	//	*Metric_Distribution1
	//	*Metric_AggregatedHistogram1
	//	*Metric_AggregatedSummary1
	//	*Metric_Distribution2
	//	*Metric_AggregatedHistogram2
	//	*Metric_AggregatedSummary2
	//	*Metric_Sketch
	//	*Metric_AggregatedHistogram3
	//	*Metric_AggregatedSummary3
	Value      isMetric_Value `protobuf_oneof:"value"`
	Namespace  string         `protobuf:"bytes,11,opt,name=namespace,proto3" json:"namespace,omitempty"`
	IntervalMs uint32         `protobuf:"varint,18,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	// Deprecated: Marked as deprecated in event.proto.
	Metadata      *Value    `protobuf:"bytes,19,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MetadataFull  *Metadata `protobuf:"bytes,21,opt,name=metadata_full,json=metadataFull,proto3" json:"metadata_full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metric) GetTagsV1() map[string]string {
	if x != nil {
		return x.TagsV1
	}
	return nil
}

func (x *Metric) GetTagsV2() map[string]*TagValues {
	if x != nil {
		return x.TagsV2
	}
	return nil
}

func (x *Metric) GetKind() Metric_Kind {
	if x != nil {
		return x.Kind
	}
	return Metric_Incremental
}

func (x *Metric) GetValue() isMetric_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metric) GetCounter() *Counter {
	if x != nil {
		if x, ok := x.Value.(*Metric_Counter); ok {
			return x.Counter
		}
	}
	return nil
}

func (x *Metric) GetGauge() *Gauge {
	if x != nil {
		if x, ok := x.Value.(*Metric_Gauge); ok {
			return x.Gauge
		}
	}
	return nil
}

func (x *Metric) GetSet() *Set {
	if x != nil {
		if x, ok := x.Value.(*Metric_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *Metric) GetDistribution1() *Distribution1 {
	if x != nil {
		if x, ok := x.Value.(*Metric_Distribution1); ok {
			return x.Distribution1
		}
	}
	return nil
}

func (x *Metric) GetAggregatedHistogram1() *AggregatedHistogram1 {
	if x != nil {
		if x, ok := x.Value.(*Metric_AggregatedHistogram1); ok {
			return x.AggregatedHistogram1
		}
	}
	return nil
}

func (x *Metric) GetAggregatedSummary1() *AggregatedSummary1 {
	if x != nil {
		if x, ok := x.Value.(*Metric_AggregatedSummary1); ok {
			return x.AggregatedSummary1
		}
	}
	return nil
}

func (x *Metric) GetDistribution2() *Distribution2 {
	if x != nil {
		if x, ok := x.Value.(*Metric_Distribution2); ok {
			return x.Distribution2
		}
	}
	return nil
}

func (x *Metric) GetAggregatedHistogram2() *AggregatedHistogram2 {
	if x != nil {
		if x, ok := x.Value.(*Metric_AggregatedHistogram2); ok {
			return x.AggregatedHistogram2
		}
	}
	return nil
}

func (x *Metric) GetAggregatedSummary2() *AggregatedSummary2 {
	if x != nil {
		if x, ok := x.Value.(*Metric_AggregatedSummary2); ok {
			return x.AggregatedSummary2
		}
	}
	return nil
}

func (x *Metric) GetSketch() *Sketch {
	if x != nil {
		if x, ok := x.Value.(*Metric_Sketch); ok {
			return x.Sketch
		}
	}
	return nil
}

func (x *Metric) GetAggregatedHistogram3() *AggregatedHistogram3 {
	if x != nil {
		if x, ok := x.Value.(*Metric_AggregatedHistogram3); ok {
			return x.AggregatedHistogram3
		}
	}
	return nil
}

func (x *Metric) GetAggregatedSummary3() *AggregatedSummary3 {
	if x != nil {
		if x, ok := x.Value.(*Metric_AggregatedSummary3); ok {
			return x.AggregatedSummary3
		}
	}
	return nil
}

func (x *Metric) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metric) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// Deprecated: Marked as deprecated in event.proto.
func (x *Metric) GetMetadata() *Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Metric) GetMetadataFull() *Metadata {
	if x != nil {
		return x.MetadataFull
	}
	return nil
}

type isMetric_Value interface {
	isMetric_Value()
}

type Metric_Counter struct {
	Counter *Counter `protobuf:"bytes,5,opt,name=counter,proto3,oneof"`
}

type Metric_Gauge struct {
	Gauge *Gauge `protobuf:"bytes,6,opt,name=gauge,proto3,oneof"`
}

type Metric_Set struct {
	Set *Set `protobuf:"bytes,7,opt,name=set,proto3,oneof"`
}

type Metric_Distribution1 struct {
	Distribution1 *Distribution1 `protobuf:"bytes,8,opt,name=distribution1,proto3,oneof"`
}

type Metric_AggregatedHistogram1 struct {
	AggregatedHistogram1 *AggregatedHistogram1 `protobuf:"bytes,9,opt,name=aggregated_histogram1,json=aggregatedHistogram1,proto3,oneof"`
}

type Metric_AggregatedSummary1 struct {
	AggregatedSummary1 *AggregatedSummary1 `protobuf:"bytes,10,opt,name=aggregated_summary1,json=aggregatedSummary1,proto3,oneof"`
}

type Metric_Distribution2 struct {
	Distribution2 *Distribution2 `protobuf:"bytes,12,opt,name=distribution2,proto3,oneof"`
}

type Metric_AggregatedHistogram2 struct {
	AggregatedHistogram2 *AggregatedHistogram2 `protobuf:"bytes,13,opt,name=aggregated_histogram2,json=aggregatedHistogram2,proto3,oneof"`
}

type Metric_AggregatedSummary2 struct {
	AggregatedSummary2 *AggregatedSummary2 `protobuf:"bytes,14,opt,name=aggregated_summary2,json=aggregatedSummary2,proto3,oneof"`
}

type Metric_Sketch struct {
	Sketch *Sketch `protobuf:"bytes,15,opt,name=sketch,proto3,oneof"`
}

type Metric_AggregatedHistogram3 struct {
	AggregatedHistogram3 *AggregatedHistogram3 `protobuf:"bytes,16,opt,name=aggregated_histogram3,json=aggregatedHistogram3,proto3,oneof"`
}

type Metric_AggregatedSummary3 struct {
	AggregatedSummary3 *AggregatedSummary3 `protobuf:"bytes,17,opt,name=aggregated_summary3,json=aggregatedSummary3,proto3,oneof"`
}

func (*Metric_Counter) isMetric_Value() {}

func (*Metric_Gauge) isMetric_Value() {}

func (*Metric_Set) isMetric_Value() {}

func (*Metric_Distribution1) isMetric_Value() {}

func (*Metric_AggregatedHistogram1) isMetric_Value() {}

func (*Metric_AggregatedSummary1) isMetric_Value() {}

func (*Metric_Distribution2) isMetric_Value() {}

func (*Metric_AggregatedHistogram2) isMetric_Value() {}

func (*Metric_AggregatedSummary2) isMetric_Value() {}

func (*Metric_Sketch) isMetric_Value() {}

func (*Metric_AggregatedHistogram3) isMetric_Value() {}

func (*Metric_AggregatedSummary3) isMetric_Value() {}

type TagValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*TagValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagValues) Reset() {
	*x = TagValues{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagValues) ProtoMessage() {}

func (x *TagValues) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagValues.ProtoReflect.Descriptor instead.
func (*TagValues) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *TagValues) GetValues() []*TagValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type TagValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagValue) Reset() {
	*x = TagValue{}
	mi := &file_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagValue) ProtoMessage() {}

func (x *TagValue) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagValue.ProtoReflect.Descriptor instead.
func (*TagValue) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{16}
}

func (x *TagValue) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{17}
}

func (x *Counter) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Gauge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gauge) Reset() {
	*x = Gauge{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gauge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gauge) ProtoMessage() {}

func (x *Gauge) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gauge.ProtoReflect.Descriptor instead.
func (*Gauge) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{18}
}

func (x *Gauge) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Set struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Set) Reset() {
	*x = Set{}
	mi := &file_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{19}
}

func (x *Set) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Distribution1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	SampleRates   []uint32               `protobuf:"varint,2,rep,packed,name=sample_rates,json=sampleRates,proto3" json:"sample_rates,omitempty"`
	Statistic     StatisticKind          `protobuf:"varint,3,opt,name=statistic,proto3,enum=event.StatisticKind" json:"statistic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution1) Reset() {
	*x = Distribution1{}
	mi := &file_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution1) ProtoMessage() {}

func (x *Distribution1) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution1.ProtoReflect.Descriptor instead.
func (*Distribution1) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{20}
}

func (x *Distribution1) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Distribution1) GetSampleRates() []uint32 {
	if x != nil {
		return x.SampleRates
	}
	return nil
}

func (x *Distribution1) GetStatistic() StatisticKind {
	if x != nil {
		return x.Statistic
	}
	return StatisticKind_Histogram
}

type Distribution2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*DistributionSample  `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	Statistic     StatisticKind          `protobuf:"varint,2,opt,name=statistic,proto3,enum=event.StatisticKind" json:"statistic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution2) Reset() {
	*x = Distribution2{}
	mi := &file_event_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution2) ProtoMessage() {}

func (x *Distribution2) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution2.ProtoReflect.Descriptor instead.
func (*Distribution2) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{21}
}

func (x *Distribution2) GetSamples() []*DistributionSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *Distribution2) GetStatistic() StatisticKind {
	if x != nil {
		return x.Statistic
	}
	return StatisticKind_Histogram
}

type DistributionSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Rate          uint32                 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributionSample) Reset() {
	*x = DistributionSample{}
	mi := &file_event_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributionSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionSample) ProtoMessage() {}

func (x *DistributionSample) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionSample.ProtoReflect.Descriptor instead.
func (*DistributionSample) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{22}
}

func (x *DistributionSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DistributionSample) GetRate() uint32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type AggregatedHistogram1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []float64              `protobuf:"fixed64,1,rep,packed,name=buckets,proto3" json:"buckets,omitempty"`
	Counts        []uint32               `protobuf:"varint,2,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Sum           float64                `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedHistogram1) Reset() {
	*x = AggregatedHistogram1{}
	mi := &file_event_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedHistogram1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedHistogram1) ProtoMessage() {}

func (x *AggregatedHistogram1) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedHistogram1.ProtoReflect.Descriptor instead.
func (*AggregatedHistogram1) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{23}
}

func (x *AggregatedHistogram1) GetBuckets() []float64 {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *AggregatedHistogram1) GetCounts() []uint32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *AggregatedHistogram1) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregatedHistogram1) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type AggregatedHistogram2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*HistogramBucket     `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Sum           float64                `protobuf:"fixed64,3,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedHistogram2) Reset() {
	*x = AggregatedHistogram2{}
	mi := &file_event_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedHistogram2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedHistogram2) ProtoMessage() {}

func (x *AggregatedHistogram2) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedHistogram2.ProtoReflect.Descriptor instead.
func (*AggregatedHistogram2) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{24}
}

func (x *AggregatedHistogram2) GetBuckets() []*HistogramBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *AggregatedHistogram2) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregatedHistogram2) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type AggregatedHistogram3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*HistogramBucket3    `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Sum           float64                `protobuf:"fixed64,3,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedHistogram3) Reset() {
	*x = AggregatedHistogram3{}
	mi := &file_event_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedHistogram3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedHistogram3) ProtoMessage() {}

func (x *AggregatedHistogram3) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedHistogram3.ProtoReflect.Descriptor instead.
func (*AggregatedHistogram3) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{25}
}

func (x *AggregatedHistogram3) GetBuckets() []*HistogramBucket3 {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *AggregatedHistogram3) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregatedHistogram3) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type HistogramBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpperLimit    float64                `protobuf:"fixed64,1,opt,name=upper_limit,json=upperLimit,proto3" json:"upper_limit,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramBucket) Reset() {
	*x = HistogramBucket{}
	mi := &file_event_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramBucket) ProtoMessage() {}

func (x *HistogramBucket) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramBucket.ProtoReflect.Descriptor instead.
func (*HistogramBucket) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{26}
}

func (x *HistogramBucket) GetUpperLimit() float64 {
	if x != nil {
		return x.UpperLimit
	}
	return 0
}

func (x *HistogramBucket) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type HistogramBucket3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpperLimit    float64                `protobuf:"fixed64,1,opt,name=upper_limit,json=upperLimit,proto3" json:"upper_limit,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramBucket3) Reset() {
	*x = HistogramBucket3{}
	mi := &file_event_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramBucket3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramBucket3) ProtoMessage() {}

func (x *HistogramBucket3) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramBucket3.ProtoReflect.Descriptor instead.
func (*HistogramBucket3) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{27}
}

func (x *HistogramBucket3) GetUpperLimit() float64 {
	if x != nil {
		return x.UpperLimit
	}
	return 0
}

func (x *HistogramBucket3) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AggregatedSummary1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantiles     []float64              `protobuf:"fixed64,1,rep,packed,name=quantiles,proto3" json:"quantiles,omitempty"`
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Sum           float64                `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedSummary1) Reset() {
	*x = AggregatedSummary1{}
	mi := &file_event_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedSummary1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedSummary1) ProtoMessage() {}

func (x *AggregatedSummary1) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedSummary1.ProtoReflect.Descriptor instead.
func (*AggregatedSummary1) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{28}
}

func (x *AggregatedSummary1) GetQuantiles() []float64 {
	if x != nil {
		return x.Quantiles
	}
	return nil
}

func (x *AggregatedSummary1) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *AggregatedSummary1) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregatedSummary1) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type AggregatedSummary2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantiles     []*SummaryQuantile     `protobuf:"bytes,1,rep,name=quantiles,proto3" json:"quantiles,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Sum           float64                `protobuf:"fixed64,3,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedSummary2) Reset() {
	*x = AggregatedSummary2{}
	mi := &file_event_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedSummary2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedSummary2) ProtoMessage() {}

func (x *AggregatedSummary2) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedSummary2.ProtoReflect.Descriptor instead.
func (*AggregatedSummary2) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{29}
}

func (x *AggregatedSummary2) GetQuantiles() []*SummaryQuantile {
	if x != nil {
		return x.Quantiles
	}
	return nil
}

func (x *AggregatedSummary2) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregatedSummary2) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type AggregatedSummary3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantiles     []*SummaryQuantile     `protobuf:"bytes,1,rep,name=quantiles,proto3" json:"quantiles,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Sum           float64                `protobuf:"fixed64,3,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedSummary3) Reset() {
	*x = AggregatedSummary3{}
	mi := &file_event_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedSummary3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedSummary3) ProtoMessage() {}

func (x *AggregatedSummary3) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedSummary3.ProtoReflect.Descriptor instead.
func (*AggregatedSummary3) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{30}
}

func (x *AggregatedSummary3) GetQuantiles() []*SummaryQuantile {
	if x != nil {
		return x.Quantiles
	}
	return nil
}

func (x *AggregatedSummary3) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregatedSummary3) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type SummaryQuantile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantile      float64                `protobuf:"fixed64,1,opt,name=quantile,proto3" json:"quantile,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryQuantile) Reset() {
	*x = SummaryQuantile{}
	mi := &file_event_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryQuantile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryQuantile) ProtoMessage() {}

func (x *SummaryQuantile) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryQuantile.ProtoReflect.Descriptor instead.
func (*SummaryQuantile) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{31}
}

func (x *SummaryQuantile) GetQuantile() float64 {
	if x != nil {
		return x.Quantile
	}
	return 0
}

func (x *SummaryQuantile) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Sketch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sketch:
	//
	//	*Sketch_AgentDdSketch
	Sketch        isSketch_Sketch `protobuf_oneof:"sketch"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sketch) Reset() {
	*x = Sketch{}
	mi := &file_event_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sketch) ProtoMessage() {}

func (x *Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sketch.ProtoReflect.Descriptor instead.
func (*Sketch) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{32}
}

func (x *Sketch) GetSketch() isSketch_Sketch {
	if x != nil {
		return x.Sketch
	}
	return nil
}

func (x *Sketch) GetAgentDdSketch() *Sketch_AgentDDSketch {
	if x != nil {
		if x, ok := x.Sketch.(*Sketch_AgentDdSketch); ok {
			return x.AgentDdSketch
		}
	}
	return nil
}

type isSketch_Sketch interface {
	isSketch_Sketch()
}

type Sketch_AgentDdSketch struct {
	AgentDdSketch *Sketch_AgentDDSketch `protobuf:"bytes,1,opt,name=agent_dd_sketch,json=agentDdSketch,proto3,oneof"`
}

func (*Sketch_AgentDdSketch) isSketch_Sketch() {}

type Sketch_AgentDDSketch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Summary statistics for the samples in this sketch.
	Count uint32  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Min   float64 `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max   float64 `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	Sum   float64 `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`
	Avg   float64 `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	// The bins (buckets) of this sketch, where `k` and `n` are unzipped pairs.
	// `k` is the list of bin indexes that are populated, and `n` is the count of samples
	// within the given bin.
	K             []int32  `protobuf:"zigzag32,6,rep,packed,name=k,proto3" json:"k,omitempty"`
	N             []uint32 `protobuf:"varint,7,rep,packed,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sketch_AgentDDSketch) Reset() {
	*x = Sketch_AgentDDSketch{}
	mi := &file_event_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sketch_AgentDDSketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sketch_AgentDDSketch) ProtoMessage() {}

func (x *Sketch_AgentDDSketch) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sketch_AgentDDSketch.ProtoReflect.Descriptor instead.
func (*Sketch_AgentDDSketch) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{32, 0}
}

func (x *Sketch_AgentDDSketch) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Sketch_AgentDDSketch) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Sketch_AgentDDSketch) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Sketch_AgentDDSketch) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Sketch_AgentDDSketch) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *Sketch_AgentDDSketch) GetK() []int32 {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *Sketch_AgentDDSketch) GetN() []uint32 {
	if x != nil {
		return x.N
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n" +
	"\n" +
	"EventArray\x12%\n" +
	"\x04logs\x18\x01 \x01(\v2\x0f.event.LogArrayH\x00R\x04logs\x12.\n" +
	"\ametrics\x18\x02 \x01(\v2\x12.event.MetricArrayH\x00R\ametrics\x12+\n" +
	"\x06traces\x18\x03 \x01(\v2\x11.event.TraceArrayH\x00R\x06tracesB\b\n" +
	"\x06events\"*\n" +
	"\bLogArray\x12\x1e\n" +
	"\x04logs\x18\x01 \x03(\v2\n" +
	".event.LogR\x04logs\"6\n" +
	"\vMetricArray\x12'\n" +
	"\ametrics\x18\x01 \x03(\v2\r.event.MetricR\ametrics\"2\n" +
	"\n" +
	"TraceArray\x12$\n" +
	"\x06traces\x18\x01 \x03(\v2\f.event.TraceR\x06traces\"\x86\x01\n" +
	"\fEventWrapper\x12\x1e\n" +
	"\x03log\x18\x01 \x01(\v2\n" +
	".event.LogH\x00R\x03log\x12'\n" +
	"\x06metric\x18\x02 \x01(\v2\r.event.MetricH\x00R\x06metric\x12$\n" +
	"\x05trace\x18\x03 \x01(\v2\f.event.TraceH\x00R\x05traceB\a\n" +
	"\x05event\"\x86\x02\n" +
	"\x03Log\x12.\n" +
	"\x06fields\x18\x01 \x03(\v2\x16.event.Log.FieldsEntryR\x06fields\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.event.ValueR\x05value\x12,\n" +
	"\bmetadata\x18\x03 \x01(\v2\f.event.ValueB\x02\x18\x01R\bmetadata\x124\n" +
	"\rmetadata_full\x18\x04 \x01(\v2\x0f.event.MetadataR\fmetadataFull\x1aG\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.event.ValueR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x05Trace\x120\n" +
	"\x06fields\x18\x01 \x03(\v2\x18.event.Trace.FieldsEntryR\x06fields\x12,\n" +
	"\bmetadata\x18\x02 \x01(\v2\f.event.ValueB\x02\x18\x01R\bmetadata\x124\n" +
	"\rmetadata_full\x18\x03 \x01(\v2\x0f.event.MetadataR\fmetadataFull\x1aG\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.event.ValueR\x05value:\x028\x01\"\x88\x01\n" +
	"\bValueMap\x123\n" +
	"\x06fields\x18\x01 \x03(\v2\x1b.event.ValueMap.FieldsEntryR\x06fields\x1aG\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.event.ValueR\x05value:\x028\x01\"0\n" +
	"\n" +
	"ValueArray\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.event.ValueR\x05items\"\xb8\x02\n" +
	"\x05Value\x12\x1d\n" +
	"\traw_bytes\x18\x01 \x01(\fH\x00R\brawBytes\x12:\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestamp\x12\x1a\n" +
	"\ainteger\x18\x04 \x01(\x03H\x00R\ainteger\x12\x16\n" +
	"\x05float\x18\x05 \x01(\x01H\x00R\x05float\x12\x1a\n" +
	"\aboolean\x18\x06 \x01(\bH\x00R\aboolean\x12#\n" +
	"\x03map\x18\a \x01(\v2\x0f.event.ValueMapH\x00R\x03map\x12)\n" +
	"\x05array\x18\b \x01(\v2\x11.event.ValueArrayH\x00R\x05array\x12&\n" +
	"\x04null\x18\t \x01(\x0e2\x10.event.ValueNullH\x00R\x04nullB\x06\n" +
	"\x04kindJ\x04\b\x03\x10\x04\"\xd7\x01\n" +
	"\x15DatadogOriginMetadata\x12*\n" +
	"\x0eorigin_product\x18\x01 \x01(\rH\x00R\roriginProduct\x88\x01\x01\x12,\n" +
	"\x0forigin_category\x18\x02 \x01(\rH\x01R\x0eoriginCategory\x88\x01\x01\x12*\n" +
	"\x0eorigin_service\x18\x03 \x01(\rH\x02R\roriginService\x88\x01\x01B\x11\n" +
	"\x0f_origin_productB\x12\n" +
	"\x10_origin_categoryB\x11\n" +
	"\x0f_origin_service\"|\n" +
	"\aSecrets\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.event.Secrets.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\bOutputId\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x17\n" +
	"\x04port\x18\x02 \x01(\tH\x00R\x04port\x88\x01\x01B\a\n" +
	"\x05_port\"\xee\x02\n" +
	"\bMetadata\x12\"\n" +
	"\x05value\x18\x01 \x01(\v2\f.event.ValueR\x05value\x12T\n" +
	"\x17datadog_origin_metadata\x18\x02 \x01(\v2\x1c.event.DatadogOriginMetadataR\x15datadogOriginMetadata\x12 \n" +
	"\tsource_id\x18\x03 \x01(\tH\x00R\bsourceId\x88\x01\x01\x12$\n" +
	"\vsource_type\x18\x04 \x01(\tH\x01R\n" +
	"sourceType\x88\x01\x01\x120\n" +
	"\vupstream_id\x18\x05 \x01(\v2\x0f.event.OutputIdR\n" +
	"upstreamId\x12(\n" +
	"\asecrets\x18\x06 \x01(\v2\x0e.event.SecretsR\asecrets\x12&\n" +
	"\x0fsource_event_id\x18\a \x01(\fR\rsourceEventIdB\f\n" +
	"\n" +
	"_source_idB\x0e\n" +
	"\f_source_type\"\xbe\n" +
	"\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\atags_v1\x18\x03 \x03(\v2\x19.event.Metric.TagsV1EntryR\x06tagsV1\x122\n" +
	"\atags_v2\x18\x14 \x03(\v2\x19.event.Metric.TagsV2EntryR\x06tagsV2\x12&\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x12.event.Metric.KindR\x04kind\x12*\n" +
	"\acounter\x18\x05 \x01(\v2\x0e.event.CounterH\x00R\acounter\x12$\n" +
	"\x05gauge\x18\x06 \x01(\v2\f.event.GaugeH\x00R\x05gauge\x12\x1e\n" +
	"\x03set\x18\a \x01(\v2\n" +
	".event.SetH\x00R\x03set\x12<\n" +
	"\rdistribution1\x18\b \x01(\v2\x14.event.Distribution1H\x00R\rdistribution1\x12R\n" +
	"\x15aggregated_histogram1\x18\t \x01(\v2\x1b.event.AggregatedHistogram1H\x00R\x14aggregatedHistogram1\x12L\n" +
	"\x13aggregated_summary1\x18\n" +
	" \x01(\v2\x19.event.AggregatedSummary1H\x00R\x12aggregatedSummary1\x12<\n" +
	"\rdistribution2\x18\f \x01(\v2\x14.event.Distribution2H\x00R\rdistribution2\x12R\n" +
	"\x15aggregated_histogram2\x18\r \x01(\v2\x1b.event.AggregatedHistogram2H\x00R\x14aggregatedHistogram2\x12L\n" +
	"\x13aggregated_summary2\x18\x0e \x01(\v2\x19.event.AggregatedSummary2H\x00R\x12aggregatedSummary2\x12'\n" +
	"\x06sketch\x18\x0f \x01(\v2\r.event.SketchH\x00R\x06sketch\x12R\n" +
	"\x15aggregated_histogram3\x18\x10 \x01(\v2\x1b.event.AggregatedHistogram3H\x00R\x14aggregatedHistogram3\x12L\n" +
	"\x13aggregated_summary3\x18\x11 \x01(\v2\x19.event.AggregatedSummary3H\x00R\x12aggregatedSummary3\x12\x1c\n" +
	"\tnamespace\x18\v \x01(\tR\tnamespace\x12\x1f\n" +
	"\vinterval_ms\x18\x12 \x01(\rR\n" +
	"intervalMs\x12,\n" +
	"\bmetadata\x18\x13 \x01(\v2\f.event.ValueB\x02\x18\x01R\bmetadata\x124\n" +
	"\rmetadata_full\x18\x15 \x01(\v2\x0f.event.MetadataR\fmetadataFull\x1a9\n" +
	"\vTagsV1Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aK\n" +
	"\vTagsV2Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.event.TagValuesR\x05value:\x028\x01\"%\n" +
	"\x04Kind\x12\x0f\n" +
	"\vIncremental\x10\x00\x12\f\n" +
	"\bAbsolute\x10\x01B\a\n" +
	"\x05value\"4\n" +
	"\tTagValues\x12'\n" +
	"\x06values\x18\x01 \x03(\v2\x0f.event.TagValueR\x06values\"/\n" +
	"\bTagValue\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\x1f\n" +
	"\aCounter\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"\x1d\n" +
	"\x05Gauge\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"\x1d\n" +
	"\x03Set\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"~\n" +
	"\rDistribution1\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x12!\n" +
	"\fsample_rates\x18\x02 \x03(\rR\vsampleRates\x122\n" +
	"\tstatistic\x18\x03 \x01(\x0e2\x14.event.StatisticKindR\tstatistic\"x\n" +
	"\rDistribution2\x123\n" +
	"\asamples\x18\x01 \x03(\v2\x19.event.DistributionSampleR\asamples\x122\n" +
	"\tstatistic\x18\x02 \x01(\x0e2\x14.event.StatisticKindR\tstatistic\">\n" +
	"\x12DistributionSample\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\rR\x04rate\"p\n" +
	"\x14AggregatedHistogram1\x12\x18\n" +
	"\abuckets\x18\x01 \x03(\x01R\abuckets\x12\x16\n" +
	"\x06counts\x18\x02 \x03(\rR\x06counts\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\x01R\x03sum\"p\n" +
	"\x14AggregatedHistogram2\x120\n" +
	"\abuckets\x18\x01 \x03(\v2\x16.event.HistogramBucketR\abuckets\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x01R\x03sum\"q\n" +
	"\x14AggregatedHistogram3\x121\n" +
	"\abuckets\x18\x01 \x03(\v2\x17.event.HistogramBucket3R\abuckets\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x01R\x03sum\"H\n" +
	"\x0fHistogramBucket\x12\x1f\n" +
	"\vupper_limit\x18\x01 \x01(\x01R\n" +
	"upperLimit\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"I\n" +
	"\x10HistogramBucket3\x12\x1f\n" +
	"\vupper_limit\x18\x01 \x01(\x01R\n" +
	"upperLimit\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"r\n" +
	"\x12AggregatedSummary1\x12\x1c\n" +
	"\tquantiles\x18\x01 \x03(\x01R\tquantiles\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\x01R\x03sum\"r\n" +
	"\x12AggregatedSummary2\x124\n" +
	"\tquantiles\x18\x01 \x03(\v2\x16.event.SummaryQuantileR\tquantiles\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x01R\x03sum\"r\n" +
	"\x12AggregatedSummary3\x124\n" +
	"\tquantiles\x18\x01 \x03(\v2\x16.event.SummaryQuantileR\tquantiles\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x01R\x03sum\"C\n" +
	"\x0fSummaryQuantile\x12\x1a\n" +
	"\bquantile\x18\x01 \x01(\x01R\bquantile\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xe5\x01\n" +
	"\x06Sketch\x12E\n" +
	"\x0fagent_dd_sketch\x18\x01 \x01(\v2\x1b.event.Sketch.AgentDDSketchH\x00R\ragentDdSketch\x1a\x89\x01\n" +
	"\rAgentDDSketch\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x01R\x03max\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03avg\x18\x05 \x01(\x01R\x03avg\x12\f\n" +
	"\x01k\x18\x06 \x03(\x11R\x01k\x12\f\n" +
	"\x01n\x18\a \x03(\rR\x01nB\b\n" +
	"\x06sketch*\x1b\n" +
	"\tValueNull\x12\x0e\n" +
	"\n" +
	"NULL_VALUE\x10\x00*+\n" +
	"\rStatisticKind\x12\r\n" +
	"\tHistogram\x10\x00\x12\v\n" +
	"\aSummary\x10\x01b\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_event_proto_goTypes = []any{
	(ValueNull)(0),                // 0: event.ValueNull
	(StatisticKind)(0),            // 1: event.StatisticKind
	(Metric_Kind)(0),              // 2: event.Metric.Kind
	(*EventArray)(nil),            // 3: event.EventArray
	(*LogArray)(nil),              // 4: event.LogArray
	(*MetricArray)(nil),           // 5: event.MetricArray
	(*TraceArray)(nil),            // 6: event.TraceArray
	(*EventWrapper)(nil),          // 7: event.EventWrapper
	(*Log)(nil),                   // 8: event.Log
	(*Trace)(nil),                 // 9: event.Trace
	(*ValueMap)(nil),              // 10: event.ValueMap
	(*ValueArray)(nil),            // 11: event.ValueArray
	(*Value)(nil),                 // 12: event.Value
	(*DatadogOriginMetadata)(nil), // 13: event.DatadogOriginMetadata
	(*Secrets)(nil),               // 14: event.Secrets
	(*OutputId)(nil),              // 15: event.OutputId
	(*Metadata)(nil),              // 16: event.Metadata
	(*Metric)(nil),                // 17: event.Metric
	(*TagValues)(nil),             // 18: event.TagValues
	(*TagValue)(nil),              // 19: event.TagValue
	(*Counter)(nil),               // 20: event.Counter
	(*Gauge)(nil),                 // 21: event.Gauge
	(*Set)(nil),                   // 22: event.Set
	(*Distribution1)(nil),         // 23: event.Distribution1
	(*Distribution2)(nil),         // 24: event.Distribution2
	(*DistributionSample)(nil),    // 25: event.DistributionSample
	(*AggregatedHistogram1)(nil),  // 26: event.AggregatedHistogram1
	(*AggregatedHistogram2)(nil),  // 27: event.AggregatedHistogram2
	(*AggregatedHistogram3)(nil),  // 28: event.AggregatedHistogram3
	(*HistogramBucket)(nil),       // 29: event.HistogramBucket
	(*HistogramBucket3)(nil),      // 30: event.HistogramBucket3
	(*AggregatedSummary1)(nil),    // 31: event.AggregatedSummary1
	(*AggregatedSummary2)(nil),    // 32: event.AggregatedSummary2
	(*AggregatedSummary3)(nil),    // 33: event.AggregatedSummary3
	(*SummaryQuantile)(nil),       // 34: event.SummaryQuantile
	(*Sketch)(nil),                // 35: event.Sketch
	nil,                           // 36: event.Log.FieldsEntry
	nil,                           // 37: event.Trace.FieldsEntry
	nil,                           // 38: event.ValueMap.FieldsEntry
	nil,                           // 39: event.Secrets.EntriesEntry
	nil,                           // 40: event.Metric.TagsV1Entry
	nil,                           // 41: event.Metric.TagsV2Entry
	(*Sketch_AgentDDSketch)(nil),  // 42: event.Sketch.AgentDDSketch
	(*timestamppb.Timestamp)(nil), // 43: google.protobuf.Timestamp
}
var file_event_proto_depIdxs = []int32{
	4,  // 0: event.EventArray.logs:type_name -> event.LogArray
	5,  // 1: event.EventArray.metrics:type_name -> event.MetricArray
	6,  // 2: event.EventArray.traces:type_name -> event.TraceArray
	8,  // 3: event.LogArray.logs:type_name -> event.Log
	17, // 4: event.MetricArray.metrics:type_name -> event.Metric
	9,  // 5: event.TraceArray.traces:type_name -> event.Trace
	8,  // 6: event.EventWrapper.log:type_name -> event.Log
	17, // 7: event.EventWrapper.metric:type_name -> event.Metric
	9,  // 8: event.EventWrapper.trace:type_name -> event.Trace
	36, // 9: event.Log.fields:type_name -> event.Log.FieldsEntry
	12, // 10: event.Log.value:type_name -> event.Value
	12, // 11: event.Log.metadata:type_name -> event.Value
	16, // 12: event.Log.metadata_full:type_name -> event.Metadata
	37, // 13: event.Trace.fields:type_name -> event.Trace.FieldsEntry
	12, // 14: event.Trace.metadata:type_name -> event.Value
	16, // 15: event.Trace.metadata_full:type_name -> event.Metadata
	38, // 16: event.ValueMap.fields:type_name -> event.ValueMap.FieldsEntry
	12, // 17: event.ValueArray.items:type_name -> event.Value
	43, // 18: event.Value.timestamp:type_name -> google.protobuf.Timestamp
	10, // 19: event.Value.map:type_name -> event.ValueMap
	11, // 20: event.Value.array:type_name -> event.ValueArray
	0,  // 21: event.Value.null:type_name -> event.ValueNull
	39, // 22: event.Secrets.entries:type_name -> event.Secrets.EntriesEntry
	12, // 23: event.Metadata.value:type_name -> event.Value
	13, // 24: event.Metadata.datadog_origin_metadata:type_name -> event.DatadogOriginMetadata
	15, // 25: event.Metadata.upstream_id:type_name -> event.OutputId
	14, // 26: event.Metadata.secrets:type_name -> event.Secrets
	43, // 27: event.Metric.timestamp:type_name -> google.protobuf.Timestamp
	40, // 28: event.Metric.tags_v1:type_name -> event.Metric.TagsV1Entry
	41, // 29: event.Metric.tags_v2:type_name -> event.Metric.TagsV2Entry
	2,  // 30: event.Metric.kind:type_name -> event.Metric.Kind
	20, // 31: event.Metric.counter:type_name -> event.Counter
	21, // 32: event.Metric.gauge:type_name -> event.Gauge
	22, // 33: event.Metric.set:type_name -> event.Set
	23, // 34: event.Metric.distribution1:type_name -> event.Distribution1
	26, // 35: event.Metric.aggregated_histogram1:type_name -> event.AggregatedHistogram1
	31, // 36: event.Metric.aggregated_summary1:type_name -> event.AggregatedSummary1
	24, // 37: event.Metric.distribution2:type_name -> event.Distribution2
	27, // 38: event.Metric.aggregated_histogram2:type_name -> event.AggregatedHistogram2
	32, // 39: event.Metric.aggregated_summary2:type_name -> event.AggregatedSummary2
	35, // 40: event.Metric.sketch:type_name -> event.Sketch
	28, // 41: event.Metric.aggregated_histogram3:type_name -> event.AggregatedHistogram3
	33, // 42: event.Metric.aggregated_summary3:type_name -> event.AggregatedSummary3
	12, // 43: event.Metric.metadata:type_name -> event.Value
	16, // 44: event.Metric.metadata_full:type_name -> event.Metadata
	19, // 45: event.TagValues.values:type_name -> event.TagValue
	1,  // 46: event.Distribution1.statistic:type_name -> event.StatisticKind
	25, // 47: event.Distribution2.samples:type_name -> event.DistributionSample
	1,  // 48: event.Distribution2.statistic:type_name -> event.StatisticKind
	29, // 49: event.AggregatedHistogram2.buckets:type_name -> event.HistogramBucket
	30, // 50: event.AggregatedHistogram3.buckets:type_name -> event.HistogramBucket3
	34, // 51: event.AggregatedSummary2.quantiles:type_name -> event.SummaryQuantile
	34, // 52: event.AggregatedSummary3.quantiles:type_name -> event.SummaryQuantile
	42, // 53: event.Sketch.agent_dd_sketch:type_name -> event.Sketch.AgentDDSketch
	12, // 54: event.Log.FieldsEntry.value:type_name -> event.Value
	12, // 55: event.Trace.FieldsEntry.value:type_name -> event.Value
	12, // 56: event.ValueMap.FieldsEntry.value:type_name -> event.Value
	18, // 57: event.Metric.TagsV2Entry.value:type_name -> event.TagValues
	58, // [58:58] is the sub-list for method output_type
	58, // [58:58] is the sub-list for method input_type
	58, // [58:58] is the sub-list for extension type_name
	58, // [58:58] is the sub-list for extension extendee
	0,  // [0:58] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[0].OneofWrappers = []any{
		(*EventArray_Logs)(nil),
		(*EventArray_Metrics)(nil),
		(*EventArray_Traces)(nil),
	}
	file_event_proto_msgTypes[4].OneofWrappers = []any{
		(*EventWrapper_Log)(nil),
		(*EventWrapper_Metric)(nil),
		(*EventWrapper_Trace)(nil),
	}
	file_event_proto_msgTypes[9].OneofWrappers = []any{
		(*Value_RawBytes)(nil),
		(*Value_Timestamp)(nil),
		(*Value_Integer)(nil),
		(*Value_Float)(nil),
		(*Value_Boolean)(nil),
		(*Value_Map)(nil),
		(*Value_Array)(nil),
		(*Value_Null)(nil),
	}
	file_event_proto_msgTypes[10].OneofWrappers = []any{}
	file_event_proto_msgTypes[12].OneofWrappers = []any{}
	file_event_proto_msgTypes[13].OneofWrappers = []any{}
	file_event_proto_msgTypes[14].OneofWrappers = []any{
		(*Metric_Counter)(nil),
		(*Metric_Gauge)(nil),
		(*Metric_Set)(nil),
		(*Metric_Distribution1)(nil),
		(*Metric_AggregatedHistogram1)(nil),
		(*Metric_AggregatedSummary1)(nil),
		(*Metric_Distribution2)(nil),
		(*Metric_AggregatedHistogram2)(nil),
		(*Metric_AggregatedSummary2)(nil),
		(*Metric_Sketch)(nil),
		(*Metric_AggregatedHistogram3)(nil),
		(*Metric_AggregatedSummary3)(nil),
	}
	file_event_proto_msgTypes[16].OneofWrappers = []any{}
	file_event_proto_msgTypes[32].OneofWrappers = []any{
		(*Sketch_AgentDdSketch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
