// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: observability.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComponentType int32

const (
	ComponentType_COMPONENT_TYPE_UNSPECIFIED ComponentType = 0
	ComponentType_COMPONENT_TYPE_SOURCE      ComponentType = 1
	ComponentType_COMPONENT_TYPE_TRANSFORM   ComponentType = 2
	ComponentType_COMPONENT_TYPE_SINK        ComponentType = 3
)

// Enum value maps for ComponentType.
var (
	ComponentType_name = map[int32]string{
		0: "COMPONENT_TYPE_UNSPECIFIED",
		1: "COMPONENT_TYPE_SOURCE",
		2: "COMPONENT_TYPE_TRANSFORM",
		3: "COMPONENT_TYPE_SINK",
	}
	ComponentType_value = map[string]int32{
		"COMPONENT_TYPE_UNSPECIFIED": 0,
		"COMPONENT_TYPE_SOURCE":      1,
		"COMPONENT_TYPE_TRANSFORM":   2,
		"COMPONENT_TYPE_SINK":        3,
	}
)

func (x ComponentType) Enum() *ComponentType {
	p := new(ComponentType)
	*p = x
	return p
}

func (x ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_proto_enumTypes[0].Descriptor()
}

func (ComponentType) Type() protoreflect.EnumType {
	return &file_observability_proto_enumTypes[0]
}

func (x ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentType.Descriptor instead.
func (ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{0}
}

// Identifies which per-component metric to stream via StreamComponentMetrics.
type MetricName int32

const (
	MetricName_METRIC_NAME_UNSPECIFIED                MetricName = 0
	MetricName_METRIC_NAME_RECEIVED_EVENTS_THROUGHPUT MetricName = 1
	MetricName_METRIC_NAME_SENT_EVENTS_THROUGHPUT     MetricName = 2
	MetricName_METRIC_NAME_RECEIVED_BYTES_THROUGHPUT  MetricName = 3
	MetricName_METRIC_NAME_SENT_BYTES_THROUGHPUT      MetricName = 4
	MetricName_METRIC_NAME_RECEIVED_EVENTS_TOTAL      MetricName = 5
	MetricName_METRIC_NAME_SENT_EVENTS_TOTAL          MetricName = 6
	MetricName_METRIC_NAME_RECEIVED_BYTES_TOTAL       MetricName = 7
	MetricName_METRIC_NAME_SENT_BYTES_TOTAL           MetricName = 8
	MetricName_METRIC_NAME_ERRORS_TOTAL               MetricName = 9
)

// Enum value maps for MetricName.
var (
	MetricName_name = map[int32]string{
		0: "METRIC_NAME_UNSPECIFIED",
		1: "METRIC_NAME_RECEIVED_EVENTS_THROUGHPUT",
		2: "METRIC_NAME_SENT_EVENTS_THROUGHPUT",
		3: "METRIC_NAME_RECEIVED_BYTES_THROUGHPUT",
		4: "METRIC_NAME_SENT_BYTES_THROUGHPUT",
		5: "METRIC_NAME_RECEIVED_EVENTS_TOTAL",
		6: "METRIC_NAME_SENT_EVENTS_TOTAL",
		7: "METRIC_NAME_RECEIVED_BYTES_TOTAL",
		8: "METRIC_NAME_SENT_BYTES_TOTAL",
		9: "METRIC_NAME_ERRORS_TOTAL",
	}
	MetricName_value = map[string]int32{
		"METRIC_NAME_UNSPECIFIED":                0,
		"METRIC_NAME_RECEIVED_EVENTS_THROUGHPUT": 1,
		"METRIC_NAME_SENT_EVENTS_THROUGHPUT":     2,
		"METRIC_NAME_RECEIVED_BYTES_THROUGHPUT":  3,
		"METRIC_NAME_SENT_BYTES_THROUGHPUT":      4,
		"METRIC_NAME_RECEIVED_EVENTS_TOTAL":      5,
		"METRIC_NAME_SENT_EVENTS_TOTAL":          6,
		"METRIC_NAME_RECEIVED_BYTES_TOTAL":       7,
		"METRIC_NAME_SENT_BYTES_TOTAL":           8,
		"METRIC_NAME_ERRORS_TOTAL":               9,
	}
)

func (x MetricName) Enum() *MetricName {
	p := new(MetricName)
	*p = x
	return p
}

func (x MetricName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricName) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_proto_enumTypes[1].Descriptor()
}

func (MetricName) Type() protoreflect.EnumType {
	return &file_observability_proto_enumTypes[1]
}

func (x MetricName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricName.Descriptor instead.
func (MetricName) EnumDescriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{1}
}

type GetMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetaRequest) Reset() {
	*x = GetMetaRequest{}
	mi := &file_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaRequest) ProtoMessage() {}

func (x *GetMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaRequest.ProtoReflect.Descriptor instead.
func (*GetMetaRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{0}
}

type GetMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetaResponse) Reset() {
	*x = GetMetaResponse{}
	mi := &file_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaResponse) ProtoMessage() {}

func (x *GetMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaResponse.ProtoReflect.Descriptor instead.
func (*GetMetaResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetaResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetMetaResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetAllocationTracingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllocationTracingStatusRequest) Reset() {
	*x = GetAllocationTracingStatusRequest{}
	mi := &file_observability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllocationTracingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllocationTracingStatusRequest) ProtoMessage() {}

func (x *GetAllocationTracingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllocationTracingStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAllocationTracingStatusRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{2}
}

type GetAllocationTracingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllocationTracingStatusResponse) Reset() {
	*x = GetAllocationTracingStatusResponse{}
	mi := &file_observability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllocationTracingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllocationTracingStatusResponse) ProtoMessage() {}

func (x *GetAllocationTracingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllocationTracingStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAllocationTracingStatusResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllocationTracingStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetComponentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of components to return (0 = no limit)
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetComponentsRequest) Reset() {
	*x = GetComponentsRequest{}
	mi := &file_observability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComponentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComponentsRequest) ProtoMessage() {}

func (x *GetComponentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComponentsRequest.ProtoReflect.Descriptor instead.
func (*GetComponentsRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{4}
}

func (x *GetComponentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetComponentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Components    []*Component           `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetComponentsResponse) Reset() {
	*x = GetComponentsResponse{}
	mi := &file_observability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComponentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComponentsResponse) ProtoMessage() {}

func (x *GetComponentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComponentsResponse.ProtoReflect.Descriptor instead.
func (*GetComponentsResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{5}
}

func (x *GetComponentsResponse) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	ComponentType ComponentType          `protobuf:"varint,2,opt,name=component_type,json=componentType,proto3,enum=vector.observability.v1.ComponentType" json:"component_type,omitempty"`
	OnType        string                 `protobuf:"bytes,3,opt,name=on_type,json=onType,proto3" json:"on_type,omitempty"` // The specific component type name (e.g., "file", "http")
	Outputs       []*Output              `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Metrics       *ComponentMetrics      `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_observability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{6}
}

func (x *Component) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *Component) GetComponentType() ComponentType {
	if x != nil {
		return x.ComponentType
	}
	return ComponentType_COMPONENT_TYPE_UNSPECIFIED
}

func (x *Component) GetOnType() string {
	if x != nil {
		return x.OnType
	}
	return ""
}

func (x *Component) GetOutputs() []*Output {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Component) GetMetrics() *ComponentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Output struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OutputId        string                 `protobuf:"bytes,1,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	SentEventsTotal int64                  `protobuf:"varint,2,opt,name=sent_events_total,json=sentEventsTotal,proto3" json:"sent_events_total,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_observability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{7}
}

func (x *Output) GetOutputId() string {
	if x != nil {
		return x.OutputId
	}
	return ""
}

func (x *Output) GetSentEventsTotal() int64 {
	if x != nil {
		return x.SentEventsTotal
	}
	return 0
}

type ComponentMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReceivedBytesTotal  *int64                 `protobuf:"varint,1,opt,name=received_bytes_total,json=receivedBytesTotal,proto3,oneof" json:"received_bytes_total,omitempty"`
	ReceivedEventsTotal *int64                 `protobuf:"varint,2,opt,name=received_events_total,json=receivedEventsTotal,proto3,oneof" json:"received_events_total,omitempty"`
	SentBytesTotal      *int64                 `protobuf:"varint,3,opt,name=sent_bytes_total,json=sentBytesTotal,proto3,oneof" json:"sent_bytes_total,omitempty"`
	SentEventsTotal     *int64                 `protobuf:"varint,4,opt,name=sent_events_total,json=sentEventsTotal,proto3,oneof" json:"sent_events_total,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ComponentMetrics) Reset() {
	*x = ComponentMetrics{}
	mi := &file_observability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentMetrics) ProtoMessage() {}

func (x *ComponentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentMetrics.ProtoReflect.Descriptor instead.
func (*ComponentMetrics) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{8}
}

func (x *ComponentMetrics) GetReceivedBytesTotal() int64 {
	if x != nil && x.ReceivedBytesTotal != nil {
		return *x.ReceivedBytesTotal
	}
	return 0
}

func (x *ComponentMetrics) GetReceivedEventsTotal() int64 {
	if x != nil && x.ReceivedEventsTotal != nil {
		return *x.ReceivedEventsTotal
	}
	return 0
}

func (x *ComponentMetrics) GetSentBytesTotal() int64 {
	if x != nil && x.SentBytesTotal != nil {
		return *x.SentBytesTotal
	}
	return 0
}

func (x *ComponentMetrics) GetSentEventsTotal() int64 {
	if x != nil && x.SentEventsTotal != nil {
		return *x.SentEventsTotal
	}
	return 0
}

type StreamComponentAllocatedBytesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update interval in milliseconds
	IntervalMs    int32 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamComponentAllocatedBytesRequest) Reset() {
	*x = StreamComponentAllocatedBytesRequest{}
	mi := &file_observability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamComponentAllocatedBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamComponentAllocatedBytesRequest) ProtoMessage() {}

func (x *StreamComponentAllocatedBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamComponentAllocatedBytesRequest.ProtoReflect.Descriptor instead.
func (*StreamComponentAllocatedBytesRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{9}
}

func (x *StreamComponentAllocatedBytesRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type StreamComponentMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update interval in milliseconds
	IntervalMs    int32      `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	Metric        MetricName `protobuf:"varint,2,opt,name=metric,proto3,enum=vector.observability.v1.MetricName" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamComponentMetricsRequest) Reset() {
	*x = StreamComponentMetricsRequest{}
	mi := &file_observability_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamComponentMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamComponentMetricsRequest) ProtoMessage() {}

func (x *StreamComponentMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamComponentMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamComponentMetricsRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{10}
}

func (x *StreamComponentMetricsRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *StreamComponentMetricsRequest) GetMetric() MetricName {
	if x != nil {
		return x.Metric
	}
	return MetricName_METRIC_NAME_UNSPECIFIED
}

// Cumulative total value for a component metric.
// output_totals is only populated for METRIC_NAME_SENT_EVENTS_TOTAL.
type TotalMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	OutputTotals  map[string]int64       `protobuf:"bytes,2,rep,name=output_totals,json=outputTotals,proto3" json:"output_totals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalMetric) Reset() {
	*x = TotalMetric{}
	mi := &file_observability_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalMetric) ProtoMessage() {}

func (x *TotalMetric) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalMetric.ProtoReflect.Descriptor instead.
func (*TotalMetric) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{11}
}

func (x *TotalMetric) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TotalMetric) GetOutputTotals() map[string]int64 {
	if x != nil {
		return x.OutputTotals
	}
	return nil
}

// Throughput value (per-second rate) for a component metric.
// output_throughputs is only populated for METRIC_NAME_SENT_EVENTS_THROUGHPUT.
type ThroughputMetric struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Value             float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	OutputThroughputs map[string]float64     `protobuf:"bytes,2,rep,name=output_throughputs,json=outputThroughputs,proto3" json:"output_throughputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThroughputMetric) Reset() {
	*x = ThroughputMetric{}
	mi := &file_observability_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThroughputMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThroughputMetric) ProtoMessage() {}

func (x *ThroughputMetric) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThroughputMetric.ProtoReflect.Descriptor instead.
func (*ThroughputMetric) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{12}
}

func (x *ThroughputMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ThroughputMetric) GetOutputThroughputs() map[string]float64 {
	if x != nil {
		return x.OutputThroughputs
	}
	return nil
}

type StreamComponentMetricsResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ComponentId string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*StreamComponentMetricsResponse_Total
	//	*StreamComponentMetricsResponse_Throughput
	Value         isStreamComponentMetricsResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamComponentMetricsResponse) Reset() {
	*x = StreamComponentMetricsResponse{}
	mi := &file_observability_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamComponentMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamComponentMetricsResponse) ProtoMessage() {}

func (x *StreamComponentMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamComponentMetricsResponse.ProtoReflect.Descriptor instead.
func (*StreamComponentMetricsResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{13}
}

func (x *StreamComponentMetricsResponse) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *StreamComponentMetricsResponse) GetValue() isStreamComponentMetricsResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StreamComponentMetricsResponse) GetTotal() *TotalMetric {
	if x != nil {
		if x, ok := x.Value.(*StreamComponentMetricsResponse_Total); ok {
			return x.Total
		}
	}
	return nil
}

func (x *StreamComponentMetricsResponse) GetThroughput() *ThroughputMetric {
	if x != nil {
		if x, ok := x.Value.(*StreamComponentMetricsResponse_Throughput); ok {
			return x.Throughput
		}
	}
	return nil
}

type isStreamComponentMetricsResponse_Value interface {
	isStreamComponentMetricsResponse_Value()
}

type StreamComponentMetricsResponse_Total struct {
	Total *TotalMetric `protobuf:"bytes,2,opt,name=total,proto3,oneof"`
}

type StreamComponentMetricsResponse_Throughput struct {
	Throughput *ThroughputMetric `protobuf:"bytes,3,opt,name=throughput,proto3,oneof"`
}

func (*StreamComponentMetricsResponse_Total) isStreamComponentMetricsResponse_Value() {}

func (*StreamComponentMetricsResponse_Throughput) isStreamComponentMetricsResponse_Value() {}

type StreamHeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update interval in milliseconds
	IntervalMs    int32 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHeartbeatRequest) Reset() {
	*x = StreamHeartbeatRequest{}
	mi := &file_observability_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeartbeatRequest) ProtoMessage() {}

func (x *StreamHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StreamHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{14}
}

func (x *StreamHeartbeatRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type StreamHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Utc           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=utc,proto3" json:"utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHeartbeatResponse) Reset() {
	*x = StreamHeartbeatResponse{}
	mi := &file_observability_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeartbeatResponse) ProtoMessage() {}

func (x *StreamHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StreamHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{15}
}

func (x *StreamHeartbeatResponse) GetUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.Utc
	}
	return nil
}

type StreamUptimeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update interval in milliseconds
	IntervalMs    int32 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUptimeRequest) Reset() {
	*x = StreamUptimeRequest{}
	mi := &file_observability_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUptimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUptimeRequest) ProtoMessage() {}

func (x *StreamUptimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUptimeRequest.ProtoReflect.Descriptor instead.
func (*StreamUptimeRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{16}
}

func (x *StreamUptimeRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type StreamUptimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds int64                  `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUptimeResponse) Reset() {
	*x = StreamUptimeResponse{}
	mi := &file_observability_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUptimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUptimeResponse) ProtoMessage() {}

func (x *StreamUptimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUptimeResponse.ProtoReflect.Descriptor instead.
func (*StreamUptimeResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{17}
}

func (x *StreamUptimeResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type StreamComponentAllocatedBytesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComponentId    string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	AllocatedBytes int64                  `protobuf:"varint,2,opt,name=allocated_bytes,json=allocatedBytes,proto3" json:"allocated_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamComponentAllocatedBytesResponse) Reset() {
	*x = StreamComponentAllocatedBytesResponse{}
	mi := &file_observability_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamComponentAllocatedBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamComponentAllocatedBytesResponse) ProtoMessage() {}

func (x *StreamComponentAllocatedBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamComponentAllocatedBytesResponse.ProtoReflect.Descriptor instead.
func (*StreamComponentAllocatedBytesResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{18}
}

func (x *StreamComponentAllocatedBytesResponse) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *StreamComponentAllocatedBytesResponse) GetAllocatedBytes() int64 {
	if x != nil {
		return x.AllocatedBytes
	}
	return 0
}

type StreamOutputEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Glob patterns for output component IDs to match
	OutputsPatterns []string `protobuf:"bytes,1,rep,name=outputs_patterns,json=outputsPatterns,proto3" json:"outputs_patterns,omitempty"`
	// Glob patterns for input component IDs to match (optional)
	InputsPatterns []string `protobuf:"bytes,2,rep,name=inputs_patterns,json=inputsPatterns,proto3" json:"inputs_patterns,omitempty"`
	// Maximum number of events to sample per interval. Must be >= 1.
	// Unlike GetComponents, 0 is not valid here: limit controls both the
	// reservoir size and the internal channel capacity, which require a
	// positive value.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Sampling interval in milliseconds
	IntervalMs    int32 `protobuf:"varint,4,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputEventsRequest) Reset() {
	*x = StreamOutputEventsRequest{}
	mi := &file_observability_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputEventsRequest) ProtoMessage() {}

func (x *StreamOutputEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamOutputEventsRequest) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{19}
}

func (x *StreamOutputEventsRequest) GetOutputsPatterns() []string {
	if x != nil {
		return x.OutputsPatterns
	}
	return nil
}

func (x *StreamOutputEventsRequest) GetInputsPatterns() []string {
	if x != nil {
		return x.InputsPatterns
	}
	return nil
}

func (x *StreamOutputEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *StreamOutputEventsRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type StreamOutputEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamOutputEventsResponse_TappedEvent
	//	*StreamOutputEventsResponse_Notification
	Event         isStreamOutputEventsResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputEventsResponse) Reset() {
	*x = StreamOutputEventsResponse{}
	mi := &file_observability_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputEventsResponse) ProtoMessage() {}

func (x *StreamOutputEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamOutputEventsResponse) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{20}
}

func (x *StreamOutputEventsResponse) GetEvent() isStreamOutputEventsResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamOutputEventsResponse) GetTappedEvent() *TappedEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamOutputEventsResponse_TappedEvent); ok {
			return x.TappedEvent
		}
	}
	return nil
}

func (x *StreamOutputEventsResponse) GetNotification() *EventNotification {
	if x != nil {
		if x, ok := x.Event.(*StreamOutputEventsResponse_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

type isStreamOutputEventsResponse_Event interface {
	isStreamOutputEventsResponse_Event()
}

type StreamOutputEventsResponse_TappedEvent struct {
	TappedEvent *TappedEvent `protobuf:"bytes,1,opt,name=tapped_event,json=tappedEvent,proto3,oneof"`
}

type StreamOutputEventsResponse_Notification struct {
	Notification *EventNotification `protobuf:"bytes,2,opt,name=notification,proto3,oneof"`
}

func (*StreamOutputEventsResponse_TappedEvent) isStreamOutputEventsResponse_Event() {}

func (*StreamOutputEventsResponse_Notification) isStreamOutputEventsResponse_Event() {}

// Event captured from a component with metadata about where it came from
type TappedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	ComponentType string                 `protobuf:"bytes,2,opt,name=component_type,json=componentType,proto3" json:"component_type,omitempty"`
	ComponentKind string                 `protobuf:"bytes,3,opt,name=component_kind,json=componentKind,proto3" json:"component_kind,omitempty"`
	Event         *EventWrapper          `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"` // The actual event data (uses canonical proto definition)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TappedEvent) Reset() {
	*x = TappedEvent{}
	mi := &file_observability_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TappedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TappedEvent) ProtoMessage() {}

func (x *TappedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TappedEvent.ProtoReflect.Descriptor instead.
func (*TappedEvent) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{21}
}

func (x *TappedEvent) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *TappedEvent) GetComponentType() string {
	if x != nil {
		return x.ComponentType
	}
	return ""
}

func (x *TappedEvent) GetComponentKind() string {
	if x != nil {
		return x.ComponentKind
	}
	return ""
}

func (x *TappedEvent) GetEvent() *EventWrapper {
	if x != nil {
		return x.Event
	}
	return nil
}

type EventNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventNotification) Reset() {
	*x = EventNotification{}
	mi := &file_observability_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotification) ProtoMessage() {}

func (x *EventNotification) ProtoReflect() protoreflect.Message {
	mi := &file_observability_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotification.ProtoReflect.Descriptor instead.
func (*EventNotification) Descriptor() ([]byte, []int) {
	return file_observability_proto_rawDescGZIP(), []int{22}
}

func (x *EventNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_observability_proto protoreflect.FileDescriptor

const file_observability_proto_rawDesc = "" +
	"\n" +
	"\x13observability.proto\x12\x17vector.observability.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vevent.proto\"\x10\n" +
	"\x0eGetMetaRequest\"G\n" +
	"\x0fGetMetaResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"#\n" +
	"!GetAllocationTracingStatusRequest\">\n" +
	"\"GetAllocationTracingStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\",\n" +
	"\x14GetComponentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"[\n" +
	"\x15GetComponentsResponse\x12B\n" +
	"\n" +
	"components\x18\x01 \x03(\v2\".vector.observability.v1.ComponentR\n" +
	"components\"\x96\x02\n" +
	"\tComponent\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12M\n" +
	"\x0ecomponent_type\x18\x02 \x01(\x0e2&.vector.observability.v1.ComponentTypeR\rcomponentType\x12\x17\n" +
	"\aon_type\x18\x03 \x01(\tR\x06onType\x129\n" +
	"\aoutputs\x18\x04 \x03(\v2\x1f.vector.observability.v1.OutputR\aoutputs\x12C\n" +
	"\ametrics\x18\x05 \x01(\v2).vector.observability.v1.ComponentMetricsR\ametrics\"Q\n" +
	"\x06Output\x12\x1b\n" +
	"\toutput_id\x18\x01 \x01(\tR\boutputId\x12*\n" +
	"\x11sent_events_total\x18\x02 \x01(\x03R\x0fsentEventsTotal\"\xc0\x02\n" +
	"\x10ComponentMetrics\x125\n" +
	"\x14received_bytes_total\x18\x01 \x01(\x03H\x00R\x12receivedBytesTotal\x88\x01\x01\x127\n" +
	"\x15received_events_total\x18\x02 \x01(\x03H\x01R\x13receivedEventsTotal\x88\x01\x01\x12-\n" +
	"\x10sent_bytes_total\x18\x03 \x01(\x03H\x02R\x0esentBytesTotal\x88\x01\x01\x12/\n" +
	"\x11sent_events_total\x18\x04 \x01(\x03H\x03R\x0fsentEventsTotal\x88\x01\x01B\x17\n" +
	"\x15_received_bytes_totalB\x18\n" +
	"\x16_received_events_totalB\x13\n" +
	"\x11_sent_bytes_totalB\x14\n" +
	"\x12_sent_events_total\"G\n" +
	"$StreamComponentAllocatedBytesRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\"}\n" +
	"\x1dStreamComponentMetricsRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\x12;\n" +
	"\x06metric\x18\x02 \x01(\x0e2#.vector.observability.v1.MetricNameR\x06metric\"\xc1\x01\n" +
	"\vTotalMetric\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12[\n" +
	"\routput_totals\x18\x02 \x03(\v26.vector.observability.v1.TotalMetric.OutputTotalsEntryR\foutputTotals\x1a?\n" +
	"\x11OutputTotalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xdf\x01\n" +
	"\x10ThroughputMetric\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12o\n" +
	"\x12output_throughputs\x18\x02 \x03(\v2@.vector.observability.v1.ThroughputMetric.OutputThroughputsEntryR\x11outputThroughputs\x1aD\n" +
	"\x16OutputThroughputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xd7\x01\n" +
	"\x1eStreamComponentMetricsResponse\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12<\n" +
	"\x05total\x18\x02 \x01(\v2$.vector.observability.v1.TotalMetricH\x00R\x05total\x12K\n" +
	"\n" +
	"throughput\x18\x03 \x01(\v2).vector.observability.v1.ThroughputMetricH\x00R\n" +
	"throughputB\a\n" +
	"\x05value\"9\n" +
	"\x16StreamHeartbeatRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\"G\n" +
	"\x17StreamHeartbeatResponse\x12,\n" +
	"\x03utc\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03utc\"6\n" +
	"\x13StreamUptimeRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\"=\n" +
	"\x14StreamUptimeResponse\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x03R\ruptimeSeconds\"s\n" +
	"%StreamComponentAllocatedBytesResponse\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12'\n" +
	"\x0fallocated_bytes\x18\x02 \x01(\x03R\x0eallocatedBytes\"\xa6\x01\n" +
	"\x19StreamOutputEventsRequest\x12)\n" +
	"\x10outputs_patterns\x18\x01 \x03(\tR\x0foutputsPatterns\x12'\n" +
	"\x0finputs_patterns\x18\x02 \x03(\tR\x0einputsPatterns\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vinterval_ms\x18\x04 \x01(\x05R\n" +
	"intervalMs\"\xc2\x01\n" +
	"\x1aStreamOutputEventsResponse\x12I\n" +
	"\ftapped_event\x18\x01 \x01(\v2$.vector.observability.v1.TappedEventH\x00R\vtappedEvent\x12P\n" +
	"\fnotification\x18\x02 \x01(\v2*.vector.observability.v1.EventNotificationH\x00R\fnotificationB\a\n" +
	"\x05event\"\xa9\x01\n" +
	"\vTappedEvent\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12%\n" +
	"\x0ecomponent_type\x18\x02 \x01(\tR\rcomponentType\x12%\n" +
	"\x0ecomponent_kind\x18\x03 \x01(\tR\rcomponentKind\x12)\n" +
	"\x05event\x18\x04 \x01(\v2\x13.event.EventWrapperR\x05event\"-\n" +
	"\x11EventNotification\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\x81\x01\n" +
	"\rComponentType\x12\x1e\n" +
	"\x1aCOMPONENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMPONENT_TYPE_SOURCE\x10\x01\x12\x1c\n" +
	"\x18COMPONENT_TYPE_TRANSFORM\x10\x02\x12\x17\n" +
	"\x13COMPONENT_TYPE_SINK\x10\x03*\xff\x02\n" +
	"\n" +
	"MetricName\x12\x1b\n" +
	"\x17METRIC_NAME_UNSPECIFIED\x10\x00\x12*\n" +
	"&METRIC_NAME_RECEIVED_EVENTS_THROUGHPUT\x10\x01\x12&\n" +
	"\"METRIC_NAME_SENT_EVENTS_THROUGHPUT\x10\x02\x12)\n" +
	"%METRIC_NAME_RECEIVED_BYTES_THROUGHPUT\x10\x03\x12%\n" +
	"!METRIC_NAME_SENT_BYTES_THROUGHPUT\x10\x04\x12%\n" +
	"!METRIC_NAME_RECEIVED_EVENTS_TOTAL\x10\x05\x12!\n" +
	"\x1dMETRIC_NAME_SENT_EVENTS_TOTAL\x10\x06\x12$\n" +
	" METRIC_NAME_RECEIVED_BYTES_TOTAL\x10\a\x12 \n" +
	"\x1cMETRIC_NAME_SENT_BYTES_TOTAL\x10\b\x12\x1c\n" +
	"\x18METRIC_NAME_ERRORS_TOTAL\x10\t2\x95\b\n" +
	"\x14ObservabilityService\x12\\\n" +
	"\aGetMeta\x12'.vector.observability.v1.GetMetaRequest\x1a(.vector.observability.v1.GetMetaResponse\x12n\n" +
	"\rGetComponents\x12-.vector.observability.v1.GetComponentsRequest\x1a..vector.observability.v1.GetComponentsResponse\x12\x95\x01\n" +
	"\x1aGetAllocationTracingStatus\x12:.vector.observability.v1.GetAllocationTracingStatusRequest\x1a;.vector.observability.v1.GetAllocationTracingStatusResponse\x12v\n" +
	"\x0fStreamHeartbeat\x12/.vector.observability.v1.StreamHeartbeatRequest\x1a0.vector.observability.v1.StreamHeartbeatResponse0\x01\x12m\n" +
	"\fStreamUptime\x12,.vector.observability.v1.StreamUptimeRequest\x1a-.vector.observability.v1.StreamUptimeResponse0\x01\x12\xa0\x01\n" +
	"\x1dStreamComponentAllocatedBytes\x12=.vector.observability.v1.StreamComponentAllocatedBytesRequest\x1a>.vector.observability.v1.StreamComponentAllocatedBytesResponse0\x01\x12\x8b\x01\n" +
	"\x16StreamComponentMetrics\x126.vector.observability.v1.StreamComponentMetricsRequest\x1a7.vector.observability.v1.StreamComponentMetricsResponse0\x01\x12\x7f\n" +
	"\x12StreamOutputEvents\x122.vector.observability.v1.StreamOutputEventsRequest\x1a3.vector.observability.v1.StreamOutputEventsResponse0\x01b\x06proto3"

var (
	file_observability_proto_rawDescOnce sync.Once
	file_observability_proto_rawDescData []byte
)

func file_observability_proto_rawDescGZIP() []byte {
	file_observability_proto_rawDescOnce.Do(func() {
		file_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observability_proto_rawDesc), len(file_observability_proto_rawDesc)))
	})
	return file_observability_proto_rawDescData
}

var file_observability_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_observability_proto_goTypes = []any{
	(ComponentType)(0),                            // 0: vector.observability.v1.ComponentType
	(MetricName)(0),                               // 1: vector.observability.v1.MetricName
	(*GetMetaRequest)(nil),                        // 2: vector.observability.v1.GetMetaRequest
	(*GetMetaResponse)(nil),                       // 3: vector.observability.v1.GetMetaResponse
	(*GetAllocationTracingStatusRequest)(nil),     // 4: vector.observability.v1.GetAllocationTracingStatusRequest
	(*GetAllocationTracingStatusResponse)(nil),    // 5: vector.observability.v1.GetAllocationTracingStatusResponse
	(*GetComponentsRequest)(nil),                  // 6: vector.observability.v1.GetComponentsRequest
	(*GetComponentsResponse)(nil),                 // 7: vector.observability.v1.GetComponentsResponse
	(*Component)(nil),                             // 8: vector.observability.v1.Component
	(*Output)(nil),                                // 9: vector.observability.v1.Output
	(*ComponentMetrics)(nil),                      // 10: vector.observability.v1.ComponentMetrics
	(*StreamComponentAllocatedBytesRequest)(nil),  // 11: vector.observability.v1.StreamComponentAllocatedBytesRequest
	(*StreamComponentMetricsRequest)(nil),         // 12: vector.observability.v1.StreamComponentMetricsRequest
	(*TotalMetric)(nil),                           // 13: vector.observability.v1.TotalMetric
	(*ThroughputMetric)(nil),                      // 14: vector.observability.v1.ThroughputMetric
	(*StreamComponentMetricsResponse)(nil),        // 15: vector.observability.v1.StreamComponentMetricsResponse
	(*StreamHeartbeatRequest)(nil),                // 16: vector.observability.v1.StreamHeartbeatRequest
	(*StreamHeartbeatResponse)(nil),               // 17: vector.observability.v1.StreamHeartbeatResponse
	(*StreamUptimeRequest)(nil),                   // 18: vector.observability.v1.StreamUptimeRequest
	(*StreamUptimeResponse)(nil),                  // 19: vector.observability.v1.StreamUptimeResponse
	(*StreamComponentAllocatedBytesResponse)(nil), // 20: vector.observability.v1.StreamComponentAllocatedBytesResponse
	(*StreamOutputEventsRequest)(nil),             // 21: vector.observability.v1.StreamOutputEventsRequest
	(*StreamOutputEventsResponse)(nil),            // 22: vector.observability.v1.StreamOutputEventsResponse
	(*TappedEvent)(nil),                           // 23: vector.observability.v1.TappedEvent
	(*EventNotification)(nil),                     // 24: vector.observability.v1.EventNotification
	nil,                                           // 25: vector.observability.v1.TotalMetric.OutputTotalsEntry
	nil,                                           // 26: vector.observability.v1.ThroughputMetric.OutputThroughputsEntry
	(*timestamppb.Timestamp)(nil),                 // 27: google.protobuf.Timestamp
	(*EventWrapper)(nil),                          // 28: event.EventWrapper
}
var file_observability_proto_depIdxs = []int32{
	8,  // 0: vector.observability.v1.GetComponentsResponse.components:type_name -> vector.observability.v1.Component
	0,  // 1: vector.observability.v1.Component.component_type:type_name -> vector.observability.v1.ComponentType
	9,  // 2: vector.observability.v1.Component.outputs:type_name -> vector.observability.v1.Output
	10, // 3: vector.observability.v1.Component.metrics:type_name -> vector.observability.v1.ComponentMetrics
	1,  // 4: vector.observability.v1.StreamComponentMetricsRequest.metric:type_name -> vector.observability.v1.MetricName
	25, // 5: vector.observability.v1.TotalMetric.output_totals:type_name -> vector.observability.v1.TotalMetric.OutputTotalsEntry
	26, // 6: vector.observability.v1.ThroughputMetric.output_throughputs:type_name -> vector.observability.v1.ThroughputMetric.OutputThroughputsEntry
	13, // 7: vector.observability.v1.StreamComponentMetricsResponse.total:type_name -> vector.observability.v1.TotalMetric
	14, // 8: vector.observability.v1.StreamComponentMetricsResponse.throughput:type_name -> vector.observability.v1.ThroughputMetric
	27, // 9: vector.observability.v1.StreamHeartbeatResponse.utc:type_name -> google.protobuf.Timestamp
	23, // 10: vector.observability.v1.StreamOutputEventsResponse.tapped_event:type_name -> vector.observability.v1.TappedEvent
	24, // 11: vector.observability.v1.StreamOutputEventsResponse.notification:type_name -> vector.observability.v1.EventNotification
	28, // 12: vector.observability.v1.TappedEvent.event:type_name -> event.EventWrapper
	2,  // 13: vector.observability.v1.ObservabilityService.GetMeta:input_type -> vector.observability.v1.GetMetaRequest
	6,  // 14: vector.observability.v1.ObservabilityService.GetComponents:input_type -> vector.observability.v1.GetComponentsRequest
	4,  // 15: vector.observability.v1.ObservabilityService.GetAllocationTracingStatus:input_type -> vector.observability.v1.GetAllocationTracingStatusRequest
	16, // 16: vector.observability.v1.ObservabilityService.StreamHeartbeat:input_type -> vector.observability.v1.StreamHeartbeatRequest
	18, // 17: vector.observability.v1.ObservabilityService.StreamUptime:input_type -> vector.observability.v1.StreamUptimeRequest
	11, // 18: vector.observability.v1.ObservabilityService.StreamComponentAllocatedBytes:input_type -> vector.observability.v1.StreamComponentAllocatedBytesRequest
	12, // 19: vector.observability.v1.ObservabilityService.StreamComponentMetrics:input_type -> vector.observability.v1.StreamComponentMetricsRequest
	21, // 20: vector.observability.v1.ObservabilityService.StreamOutputEvents:input_type -> vector.observability.v1.StreamOutputEventsRequest
	3,  // 21: vector.observability.v1.ObservabilityService.GetMeta:output_type -> vector.observability.v1.GetMetaResponse
	7,  // 22: vector.observability.v1.ObservabilityService.GetComponents:output_type -> vector.observability.v1.GetComponentsResponse
	5,  // 23: vector.observability.v1.ObservabilityService.GetAllocationTracingStatus:output_type -> vector.observability.v1.GetAllocationTracingStatusResponse
	17, // 24: vector.observability.v1.ObservabilityService.StreamHeartbeat:output_type -> vector.observability.v1.StreamHeartbeatResponse
	19, // 25: vector.observability.v1.ObservabilityService.StreamUptime:output_type -> vector.observability.v1.StreamUptimeResponse
	20, // 26: vector.observability.v1.ObservabilityService.StreamComponentAllocatedBytes:output_type -> vector.observability.v1.StreamComponentAllocatedBytesResponse
	15, // 27: vector.observability.v1.ObservabilityService.StreamComponentMetrics:output_type -> vector.observability.v1.StreamComponentMetricsResponse
	22, // 28: vector.observability.v1.ObservabilityService.StreamOutputEvents:output_type -> vector.observability.v1.StreamOutputEventsResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_observability_proto_init() }
func file_observability_proto_init() {
	if File_observability_proto != nil {
		return
	}
	file_event_proto_init()
	file_observability_proto_msgTypes[8].OneofWrappers = []any{}
	file_observability_proto_msgTypes[13].OneofWrappers = []any{
		(*StreamComponentMetricsResponse_Total)(nil),
		(*StreamComponentMetricsResponse_Throughput)(nil),
	}
	file_observability_proto_msgTypes[20].OneofWrappers = []any{
		(*StreamOutputEventsResponse_TappedEvent)(nil),
		(*StreamOutputEventsResponse_Notification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observability_proto_rawDesc), len(file_observability_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_observability_proto_goTypes,
		DependencyIndexes: file_observability_proto_depIdxs,
		EnumInfos:         file_observability_proto_enumTypes,
		MessageInfos:      file_observability_proto_msgTypes,
	}.Build()
	File_observability_proto = out.File
	file_observability_proto_goTypes = nil
	file_observability_proto_depIdxs = nil
}
