// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: observability.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservabilityService_GetMeta_FullMethodName                       = "/vector.observability.v1.ObservabilityService/GetMeta"
	ObservabilityService_GetComponents_FullMethodName                 = "/vector.observability.v1.ObservabilityService/GetComponents"
	ObservabilityService_GetAllocationTracingStatus_FullMethodName    = "/vector.observability.v1.ObservabilityService/GetAllocationTracingStatus"
	ObservabilityService_StreamHeartbeat_FullMethodName               = "/vector.observability.v1.ObservabilityService/StreamHeartbeat"
	ObservabilityService_StreamUptime_FullMethodName                  = "/vector.observability.v1.ObservabilityService/StreamUptime"
	ObservabilityService_StreamComponentAllocatedBytes_FullMethodName = "/vector.observability.v1.ObservabilityService/StreamComponentAllocatedBytes"
	ObservabilityService_StreamComponentMetrics_FullMethodName        = "/vector.observability.v1.ObservabilityService/StreamComponentMetrics"
	ObservabilityService_StreamOutputEvents_FullMethodName            = "/vector.observability.v1.ObservabilityService/StreamOutputEvents"
)

// ObservabilityServiceClient is the client API for ObservabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Observability service for monitoring Vector instances.
type ObservabilityServiceClient interface {
	// Get metadata about the Vector instance (version, hostname)
	GetMeta(ctx context.Context, in *GetMetaRequest, opts ...grpc.CallOption) (*GetMetaResponse, error)
	// Get information about configured components (sources, transforms, sinks)
	GetComponents(ctx context.Context, in *GetComponentsRequest, opts ...grpc.CallOption) (*GetComponentsResponse, error)
	// Check whether allocation tracing is active on this instance
	GetAllocationTracingStatus(ctx context.Context, in *GetAllocationTracingStatusRequest, opts ...grpc.CallOption) (*GetAllocationTracingStatusResponse, error)
	// Stream periodic heartbeat timestamps
	StreamHeartbeat(ctx context.Context, in *StreamHeartbeatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamHeartbeatResponse], error)
	// Stream uptime in seconds
	StreamUptime(ctx context.Context, in *StreamUptimeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamUptimeResponse], error)
	// Stream memory allocated per component
	StreamComponentAllocatedBytes(ctx context.Context, in *StreamComponentAllocatedBytesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamComponentAllocatedBytesResponse], error)
	// Stream per-component metrics (throughput or totals) for a chosen metric.
	// Replaces the former 9 per-metric streaming RPCs with a single unified endpoint.
	StreamComponentMetrics(ctx context.Context, in *StreamComponentMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamComponentMetricsResponse], error)
	// Stream events from components matching the specified patterns (replaces vector tap)
	StreamOutputEvents(ctx context.Context, in *StreamOutputEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamOutputEventsResponse], error)
}

type observabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservabilityServiceClient(cc grpc.ClientConnInterface) ObservabilityServiceClient {
	return &observabilityServiceClient{cc}
}

func (c *observabilityServiceClient) GetMeta(ctx context.Context, in *GetMetaRequest, opts ...grpc.CallOption) (*GetMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetaResponse)
	err := c.cc.Invoke(ctx, ObservabilityService_GetMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observabilityServiceClient) GetComponents(ctx context.Context, in *GetComponentsRequest, opts ...grpc.CallOption) (*GetComponentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComponentsResponse)
	err := c.cc.Invoke(ctx, ObservabilityService_GetComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observabilityServiceClient) GetAllocationTracingStatus(ctx context.Context, in *GetAllocationTracingStatusRequest, opts ...grpc.CallOption) (*GetAllocationTracingStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllocationTracingStatusResponse)
	err := c.cc.Invoke(ctx, ObservabilityService_GetAllocationTracingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observabilityServiceClient) StreamHeartbeat(ctx context.Context, in *StreamHeartbeatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamHeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObservabilityService_ServiceDesc.Streams[0], ObservabilityService_StreamHeartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamHeartbeatRequest, StreamHeartbeatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamHeartbeatClient = grpc.ServerStreamingClient[StreamHeartbeatResponse]

func (c *observabilityServiceClient) StreamUptime(ctx context.Context, in *StreamUptimeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamUptimeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObservabilityService_ServiceDesc.Streams[1], ObservabilityService_StreamUptime_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamUptimeRequest, StreamUptimeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamUptimeClient = grpc.ServerStreamingClient[StreamUptimeResponse]

func (c *observabilityServiceClient) StreamComponentAllocatedBytes(ctx context.Context, in *StreamComponentAllocatedBytesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamComponentAllocatedBytesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObservabilityService_ServiceDesc.Streams[2], ObservabilityService_StreamComponentAllocatedBytes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamComponentAllocatedBytesRequest, StreamComponentAllocatedBytesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamComponentAllocatedBytesClient = grpc.ServerStreamingClient[StreamComponentAllocatedBytesResponse]

func (c *observabilityServiceClient) StreamComponentMetrics(ctx context.Context, in *StreamComponentMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamComponentMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObservabilityService_ServiceDesc.Streams[3], ObservabilityService_StreamComponentMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamComponentMetricsRequest, StreamComponentMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamComponentMetricsClient = grpc.ServerStreamingClient[StreamComponentMetricsResponse]

func (c *observabilityServiceClient) StreamOutputEvents(ctx context.Context, in *StreamOutputEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamOutputEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObservabilityService_ServiceDesc.Streams[4], ObservabilityService_StreamOutputEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamOutputEventsRequest, StreamOutputEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamOutputEventsClient = grpc.ServerStreamingClient[StreamOutputEventsResponse]

// ObservabilityServiceServer is the server API for ObservabilityService service.
// All implementations should embed UnimplementedObservabilityServiceServer
// for forward compatibility.
//
// Observability service for monitoring Vector instances.
type ObservabilityServiceServer interface {
	// Get metadata about the Vector instance (version, hostname)
	GetMeta(context.Context, *GetMetaRequest) (*GetMetaResponse, error)
	// Get information about configured components (sources, transforms, sinks)
	GetComponents(context.Context, *GetComponentsRequest) (*GetComponentsResponse, error)
	// Check whether allocation tracing is active on this instance
	GetAllocationTracingStatus(context.Context, *GetAllocationTracingStatusRequest) (*GetAllocationTracingStatusResponse, error)
	// Stream periodic heartbeat timestamps
	StreamHeartbeat(*StreamHeartbeatRequest, grpc.ServerStreamingServer[StreamHeartbeatResponse]) error
	// Stream uptime in seconds
	StreamUptime(*StreamUptimeRequest, grpc.ServerStreamingServer[StreamUptimeResponse]) error
	// Stream memory allocated per component
	StreamComponentAllocatedBytes(*StreamComponentAllocatedBytesRequest, grpc.ServerStreamingServer[StreamComponentAllocatedBytesResponse]) error
	// Stream per-component metrics (throughput or totals) for a chosen metric.
	// Replaces the former 9 per-metric streaming RPCs with a single unified endpoint.
	StreamComponentMetrics(*StreamComponentMetricsRequest, grpc.ServerStreamingServer[StreamComponentMetricsResponse]) error
	// Stream events from components matching the specified patterns (replaces vector tap)
	StreamOutputEvents(*StreamOutputEventsRequest, grpc.ServerStreamingServer[StreamOutputEventsResponse]) error
}

// UnimplementedObservabilityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservabilityServiceServer struct{}

func (UnimplementedObservabilityServiceServer) GetMeta(context.Context, *GetMetaRequest) (*GetMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeta not implemented")
}
func (UnimplementedObservabilityServiceServer) GetComponents(context.Context, *GetComponentsRequest) (*GetComponentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComponents not implemented")
}
func (UnimplementedObservabilityServiceServer) GetAllocationTracingStatus(context.Context, *GetAllocationTracingStatusRequest) (*GetAllocationTracingStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllocationTracingStatus not implemented")
}
func (UnimplementedObservabilityServiceServer) StreamHeartbeat(*StreamHeartbeatRequest, grpc.ServerStreamingServer[StreamHeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamHeartbeat not implemented")
}
func (UnimplementedObservabilityServiceServer) StreamUptime(*StreamUptimeRequest, grpc.ServerStreamingServer[StreamUptimeResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamUptime not implemented")
}
func (UnimplementedObservabilityServiceServer) StreamComponentAllocatedBytes(*StreamComponentAllocatedBytesRequest, grpc.ServerStreamingServer[StreamComponentAllocatedBytesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamComponentAllocatedBytes not implemented")
}
func (UnimplementedObservabilityServiceServer) StreamComponentMetrics(*StreamComponentMetricsRequest, grpc.ServerStreamingServer[StreamComponentMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamComponentMetrics not implemented")
}
func (UnimplementedObservabilityServiceServer) StreamOutputEvents(*StreamOutputEventsRequest, grpc.ServerStreamingServer[StreamOutputEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamOutputEvents not implemented")
}
func (UnimplementedObservabilityServiceServer) testEmbeddedByValue() {}

// UnsafeObservabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservabilityServiceServer will
// result in compilation errors.
type UnsafeObservabilityServiceServer interface {
	mustEmbedUnimplementedObservabilityServiceServer()
}

func RegisterObservabilityServiceServer(s grpc.ServiceRegistrar, srv ObservabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedObservabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservabilityService_ServiceDesc, srv)
}

func _ObservabilityService_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_GetMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).GetMeta(ctx, req.(*GetMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservabilityService_GetComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).GetComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_GetComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).GetComponents(ctx, req.(*GetComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservabilityService_GetAllocationTracingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllocationTracingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).GetAllocationTracingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_GetAllocationTracingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).GetAllocationTracingStatus(ctx, req.(*GetAllocationTracingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservabilityService_StreamHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamHeartbeatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObservabilityServiceServer).StreamHeartbeat(m, &grpc.GenericServerStream[StreamHeartbeatRequest, StreamHeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamHeartbeatServer = grpc.ServerStreamingServer[StreamHeartbeatResponse]

func _ObservabilityService_StreamUptime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamUptimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObservabilityServiceServer).StreamUptime(m, &grpc.GenericServerStream[StreamUptimeRequest, StreamUptimeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamUptimeServer = grpc.ServerStreamingServer[StreamUptimeResponse]

func _ObservabilityService_StreamComponentAllocatedBytes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamComponentAllocatedBytesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObservabilityServiceServer).StreamComponentAllocatedBytes(m, &grpc.GenericServerStream[StreamComponentAllocatedBytesRequest, StreamComponentAllocatedBytesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamComponentAllocatedBytesServer = grpc.ServerStreamingServer[StreamComponentAllocatedBytesResponse]

func _ObservabilityService_StreamComponentMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamComponentMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObservabilityServiceServer).StreamComponentMetrics(m, &grpc.GenericServerStream[StreamComponentMetricsRequest, StreamComponentMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamComponentMetricsServer = grpc.ServerStreamingServer[StreamComponentMetricsResponse]

func _ObservabilityService_StreamOutputEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOutputEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObservabilityServiceServer).StreamOutputEvents(m, &grpc.GenericServerStream[StreamOutputEventsRequest, StreamOutputEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_StreamOutputEventsServer = grpc.ServerStreamingServer[StreamOutputEventsResponse]

// ObservabilityService_ServiceDesc is the grpc.ServiceDesc for ObservabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vector.observability.v1.ObservabilityService",
	HandlerType: (*ObservabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeta",
			Handler:    _ObservabilityService_GetMeta_Handler,
		},
		{
			MethodName: "GetComponents",
			Handler:    _ObservabilityService_GetComponents_Handler,
		},
		{
			MethodName: "GetAllocationTracingStatus",
			Handler:    _ObservabilityService_GetAllocationTracingStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHeartbeat",
			Handler:       _ObservabilityService_StreamHeartbeat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamUptime",
			Handler:       _ObservabilityService_StreamUptime_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamComponentAllocatedBytes",
			Handler:       _ObservabilityService_StreamComponentAllocatedBytes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamComponentMetrics",
			Handler:       _ObservabilityService_StreamComponentMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOutputEvents",
			Handler:       _ObservabilityService_StreamOutputEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "observability.proto",
}
